version: '3.4'

services:
  db:
    # db with some data from ls8_usgs_level1_scene pre-indexed
    build: docker/database/
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - "${DB_PORT}:5432"
    restart: always
  # Overwrite ows so it can talk to docker db
  ows:
    environment:
      DB_HOSTNAME: db
      DB_PORT: 5432
    volumes:
      - ./ows_test_cfg.py:/env/config/ows_cfg.py
